version: '3.2'
services:
  nestjs:
    build:
      context: .
    command: sh -c "npm run db:create InitalDataBase && npm run db:migrate && node dist/main"
    image: xtwiny/parkos
    depends_on:
      mysql_database:
        condition: service_healthy
      phpmyadmin:
        condition: service_started
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_HOST=parkos-mysql
      - MYSQL_DB=parkos
    volumes:
      - ./www/:/var/www/html
    ports:
      - "30001:80"
    container_name: parkos-reservation
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - ./rabbitmq.env
  # MySQL Server
  mysql_database:
    image: mysql:5.7
    healthcheck:
      test: "exit 0"
    networks:
      - backend
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=parkos
    container_name: parkos-mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql_database
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - MYSQL_DATABSE=parkos
      - PMA_HOST=mysql_database
      - PMA_PORT=3306
    volumes:
      - /session
    container_name: parkos-phpmyadmin
networks:
  backend:
  frontend:
